[package]
name = "notsuperhuman-gpui-components"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "gpui_components"

[dependencies]
app_model = { package = "notsuperhuman-app-model", path = "../app/model" }
gpui.workspace = true
unicode-segmentation = "1.12"

[dev-dependencies]
gpui = { workspace = true, features = ["test-support"] }

[lints]
workspace = true
