use super::{
    Arc, Entity, HashMap, HashSet, LongFormEditor, MailAccountPaletteState, MailAccountViewState,
    MailActionPaletteState, MailAddress, MailAttachment, MailAttachmentDownloadState,
    MailComposeDraftSave, MailComposeDraftSaveSnapshot, MailComposeMode, MailComposeSendIntent,
    MailComposeTextInputs, MailContactAddress, MailContactHistoryState, MailIdentity,
    MailMessageAction, MailSearchState, MailSignInField, MailSignInState, MailSplitDefinition,
    MailSplitInputField, MailSplitSettingsState, MailSvgIconCache, MailThread, MailThreadDetail,
    MailTriageIntent, MailTriageIntentKey, RefCell, RenderImage, TextInput, VecDeque,
};

type MailSplitTextInputs = HashMap<MailSplitInputField, Entity<TextInput>>;
type MailSignInTextInputs = HashMap<MailSignInField, Entity<TextInput>>;

#[doc(hidden)]
#[derive(Default)]
pub struct MailRuntimeState {
    pub(crate) mail_selected_thread_id: Option<String>,
    pub(crate) mail_open_thread_id: Option<String>,
    pub(crate) mail_hovered_thread_id: Option<String>,
    pub(crate) mail_hovered_message_card_id: Option<String>,
    pub(crate) mail_hovered_message_action: Option<(String, MailMessageAction)>,
    pub(crate) mail_hovered_history_message_id: Option<String>,
    pub(crate) mail_expanded_history_message_ids: HashSet<String>,
    pub(crate) mail_expanded_message_header_ids: HashSet<String>,
    pub(crate) mail_folder_drawer_open: bool,
    pub(crate) mail_action_palette: Option<MailActionPaletteState>,
    pub(crate) mail_account_palette: Option<MailAccountPaletteState>,
    pub(crate) mail_bootstrap_api: Option<Arc<dyn crate::model::MailBootstrapApi>>,
    pub(crate) mail_sign_in: Option<MailSignInState>,
    pub(crate) mail_sign_in_generation: u64,
    pub(crate) mail_sign_in_inputs: RefCell<MailSignInTextInputs>,
    pub(crate) mail_split_definitions: Vec<MailSplitDefinition>,
    pub(crate) mail_split_preferences_supported: bool,
    pub(crate) mail_split_settings_generation: u64,
    pub(crate) mail_split_settings: Option<MailSplitSettingsState>,
    pub(crate) mail_split_text_inputs: RefCell<MailSplitTextInputs>,
    pub(crate) mail_account_generation: u64,
    pub(crate) mail_switching_account_id: Option<String>,
    pub(crate) mail_account_recovery_in_flight: bool,
    pub(crate) mail_account_view_states: HashMap<String, MailAccountViewState>,
    pub(crate) mail_loading_message_page: Option<(String, usize)>,
    pub(crate) mail_workspace_refresh_generation: u64,
    pub(crate) mail_workspace_actions_in_flight: usize,
    pub(crate) mail_search_state: MailSearchState,
    pub(crate) mail_search_input: RefCell<Option<Entity<TextInput>>>,
    pub(crate) mail_thread_cache: HashMap<String, MailThread>,
    pub(crate) mail_thread_detail_cache: HashMap<String, Arc<MailThreadDetail>>,
    pub(crate) mail_selected_contact_address: Option<MailContactAddress>,
    pub(crate) mail_contact_history_request_generation: u64,
    pub(crate) mail_contact_histories: HashMap<MailContactAddress, MailContactHistoryState>,
    pub(crate) mail_open_thread_body_list_thread_id: Option<String>,
    pub(crate) mail_open_thread_body_list_width: f32,
    pub(crate) mail_loading_thread_id: Option<String>,
    pub(crate) mail_attachment_download_generation: u64,
    pub(crate) mail_attachment_download: Option<MailAttachmentDownloadState>,
    pub(crate) mail_triage_generation: u64,
    pub(crate) mail_triage_reconciled_generation: u64,
    pub(crate) mail_mark_read_after_triage: HashSet<String>,
    pub(crate) mail_mark_read_suppressed: HashSet<String>,
    pub(crate) mail_triage_preflights: HashSet<MailTriageIntentKey>,
    pub(crate) mail_triage_intents: HashMap<MailTriageIntentKey, MailTriageIntent>,
    pub(crate) mail_triage_summaries: HashMap<String, (bool, bool)>,
    pub(crate) mail_identity: Option<MailIdentity>,
    pub(crate) mail_identity_loading: bool,
    pub(crate) mail_error: Option<String>,
    pub(crate) mail_compose_mode: MailComposeMode,
    pub(crate) mail_compose_draft_id: Option<String>,
    pub(crate) mail_compose_bound_thread_id: Option<String>,
    pub(crate) mail_compose_identity_id: Option<String>,
    pub(crate) mail_compose_from: Option<MailAddress>,
    pub(crate) mail_compose_reply_to: Vec<MailAddress>,
    pub(crate) mail_compose_to: String,
    pub(crate) mail_compose_cc: String,
    pub(crate) mail_compose_subject: String,
    pub(crate) mail_compose_body: String,
    pub(crate) mail_compose_attachments: Vec<MailAttachment>,
    pub(crate) mail_compose_in_reply_to: Vec<String>,
    pub(crate) mail_compose_references: Vec<String>,
    pub(crate) mail_compose_autocomplete_selected_index: usize,
    pub(crate) mail_compose_pending: bool,
    pub(crate) mail_compose_error: Option<String>,
    pub(crate) mail_compose_autosave_generation: u64,
    pub(crate) mail_compose_autosave_scheduled_generation: Option<u64>,
    pub(crate) mail_compose_autosave_in_flight: Option<MailComposeDraftSave>,
    pub(crate) mail_compose_autosave_queued: Option<MailComposeDraftSave>,
    pub(crate) mail_compose_autosave_last_saved: Option<MailComposeDraftSaveSnapshot>,
    pub(crate) mail_compose_close_after_autosave: bool,
    pub(crate) mail_compose_send_after_autosave: Option<MailComposeSendIntent>,
    pub(crate) mail_compose_text_inputs: MailComposeTextInputs,
    pub(crate) mail_compose_body_editor: RefCell<Option<Entity<LongFormEditor>>>,
    pub(crate) mail_remote_images: HashMap<String, Arc<RenderImage>>,
    pub(crate) mail_active_remote_image_urls: HashSet<String>,
    pub(crate) mail_pending_remote_image_urls: VecDeque<String>,
    pub(crate) mail_failed_remote_image_urls: HashSet<String>,
    pub(crate) mail_remote_image_load_scheduled: bool,
    pub(crate) mail_remote_image_generation: u64,
    pub(crate) mail_svg_icon_cache: MailSvgIconCache,
    pub(crate) mail_remote_image_discovery_thread_id: Option<String>,
}
