mod accounts;
mod bootstrap;
mod cache;
mod client;
mod config;
mod gmail;
mod helpers;
mod local_file;
mod runtime;
mod split_preferences;
mod superhuman;
mod types;

pub use bootstrap::production_mail_bootstrap_api;
pub use cache::{default_mail_cache_root_dir, MailWorkspaceCache, MAIL_CACHE_DIR_ENV};
pub use client::MailLiveClient;
pub use config::MailLiveConfig;
pub use helpers::sanitize_cached_mail_summary_messages;
pub use local_file::production_mail_local_file_api;
pub use runtime::{workspace_api, MailWorkspaceRuntime};
pub(crate) use split_preferences::MailSplitPreferencesStore;
pub use types::{MailWorkspaceSummaryLoad, MailboxMessagesLoad};
