use super::{
    TextInputAction, TextInputAtomClick, TextInputChange, TextInputKeyAction,
    TextInputKeyDownPreAction, TextInputKeyPreAction, TextInputLayoutChange,
    TextInputPointerSelectionChange, TextInputPreMutationActionHandler, TextInputProps,
    TextInputStateChange, TextInputVerticalBoundaryAction,
};

pub(super) struct TextInputCallbacks {
    pub(super) on_change: Option<TextInputChange>,
    pub(super) on_change_with_state: Option<TextInputStateChange>,
    pub(super) on_selection_change: Option<TextInputStateChange>,
    pub(super) on_submit: Option<TextInputAction>,
    pub(super) on_submit_with_state: Option<TextInputKeyAction>,
    pub(super) on_key_down_before_default: Option<TextInputKeyDownPreAction>,
    pub(super) on_enter_before_default: Option<TextInputKeyPreAction>,
    pub(super) on_escape: Option<TextInputAction>,
    pub(super) on_up: Option<TextInputAction>,
    pub(super) on_down: Option<TextInputAction>,
    pub(super) on_home: Option<TextInputAction>,
    pub(super) on_end: Option<TextInputAction>,
    pub(super) on_left_before_default: Option<TextInputKeyPreAction>,
    pub(super) on_right_before_default: Option<TextInputKeyPreAction>,
    pub(super) on_left_at_start: Option<TextInputKeyAction>,
    pub(super) on_right_at_end: Option<TextInputKeyAction>,
    pub(super) on_up_at_first_visual_line: Option<TextInputVerticalBoundaryAction>,
    pub(super) on_down_at_last_visual_line: Option<TextInputVerticalBoundaryAction>,
    pub(super) on_tab: Option<TextInputAction>,
    pub(super) on_tab_with_state: Option<TextInputKeyAction>,
    pub(super) on_undo_with_state: Option<TextInputKeyAction>,
    pub(super) on_redo_with_state: Option<TextInputKeyAction>,
    pub(super) on_platform_shift_up_with_state: Option<TextInputKeyAction>,
    pub(super) on_platform_shift_down_with_state: Option<TextInputKeyAction>,
    pub(super) on_select_all_again_with_state: Option<TextInputKeyAction>,
    pub(super) on_pointer_selection: Option<TextInputPointerSelectionChange>,
    pub(super) on_pre_mutation_action: Option<TextInputPreMutationActionHandler>,
    pub(super) on_atom_click: Option<TextInputAtomClick>,
    pub(super) on_focus: Option<TextInputAction>,
    pub(super) on_backspace_when_empty: Option<TextInputAction>,
    pub(super) on_backspace_at_start: Option<TextInputKeyAction>,
    pub(super) on_delete_at_end: Option<TextInputKeyAction>,
    pub(super) on_layout_change: Option<TextInputLayoutChange>,
}

impl TextInputCallbacks {
    pub(super) fn from_props(props: &TextInputProps) -> Self {
        Self {
            on_change: props.on_change.clone(),
            on_change_with_state: props.on_change_with_state.clone(),
            on_selection_change: props.on_selection_change.clone(),
            on_submit: props.on_submit.clone(),
            on_submit_with_state: props.on_submit_with_state.clone(),
            on_key_down_before_default: props.on_key_down_before_default.clone(),
            on_enter_before_default: props.on_enter_before_default.clone(),
            on_escape: props.on_escape.clone(),
            on_up: props.on_up.clone(),
            on_down: props.on_down.clone(),
            on_home: props.on_home.clone(),
            on_end: props.on_end.clone(),
            on_left_before_default: props.on_left_before_default.clone(),
            on_right_before_default: props.on_right_before_default.clone(),
            on_left_at_start: props.on_left_at_start.clone(),
            on_right_at_end: props.on_right_at_end.clone(),
            on_up_at_first_visual_line: props.on_up_at_first_visual_line.clone(),
            on_down_at_last_visual_line: props.on_down_at_last_visual_line.clone(),
            on_tab: props.on_tab.clone(),
            on_tab_with_state: props.on_tab_with_state.clone(),
            on_undo_with_state: props.on_undo_with_state.clone(),
            on_redo_with_state: props.on_redo_with_state.clone(),
            on_platform_shift_up_with_state: props.on_platform_shift_up_with_state.clone(),
            on_platform_shift_down_with_state: props.on_platform_shift_down_with_state.clone(),
            on_select_all_again_with_state: props.on_select_all_again_with_state.clone(),
            on_pointer_selection: props.on_pointer_selection.clone(),
            on_pre_mutation_action: props.on_pre_mutation_action.clone(),
            on_atom_click: props.on_atom_click.clone(),
            on_focus: props.on_focus.clone(),
            on_backspace_when_empty: props.on_backspace_when_empty.clone(),
            on_backspace_at_start: props.on_backspace_at_start.clone(),
            on_delete_at_end: props.on_delete_at_end.clone(),
            on_layout_change: props.on_layout_change.clone(),
        }
    }
}
